stages:
  - compile
  - build
  - deploy

compile:
  stage: compile
  image: maven:3-openjdk-8
  artifacts:
    paths:
      - target/
  script:
    - mvn clean package

build:
  dependencies:
  - compile
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  artifacts:
    paths:
      - target/
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${CI_DOCKERHUB_USERNAME}" "${CI_DOCKERHUB_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy:
  stage: deploy
  image: liyinlin/kubetoolbox:iac
  script:
    - walrus config setup --insecure --server ${CD_WALRUS_SERVER} --token ${CD_WALRUS_TOKEN} --project ${CD_WALRUS_PROJECT} --environment ${CD_WALRUS_PROJECT_ENV}
    - >-
      walrus service create 
      --name ${CD_WALRUS_SERVICE_NAME}
      --template '{"name": "webservice", "version": "v0.0.2"}' 
      --attributes '{"image": "'${CI_IMAGE_NAME}':'${CI_COMMIT_SHORT_SHA}'", "ports": ["8080"]}'
