apiVersion: v1
kind: Service
metadata:
  labels:
    app: game2048
  name: game2048-svc
  namespace: game2048
spec:
  ports:
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: http-8080
  selector:
    app: game2048
  type: NodePort
